Add npath tool
bblfsh/tools pull request #3
Opened 2017-06-05 08:10 UTC by dpaz

The test files are yet to be added to the PR, I don't know where they should be.
This PR depends on [#122](https://github.com/bblfsh/sdk/pull/122)

2017-06-05 13:44 UTC, alcortesm requested changes
I guess `NpathComplexity` has to be tested on a file called `npath_test.go`

2017-06-06 07:35 UTC, dpaz commented
yes, the .go file is ok, the problem is that I have some extra files which I use to do some tests. That's are the files that I have no idea where they should be

2017-06-06 09:25 UTC, smola commented
@dpaz Let's add these extra files to a directory `fixtures`.

2017-06-06 12:15 UTC, abeaumont reviewed
I think it makes sense to have proper extension in fixture files, since we may/should have variants in different programming languages

2017-06-07 07:08 UTC, alcortesm approved these changes

2017-06-07 09:38 UTC, smola requested changes

2017-06-07 09:38 UTC, smola commented on npath.go
> +
Use an appropiate godoc comment here. For example:

```
Npath computes the NPath of functions in a *uast.Node.

PMD is considered the reference implementation to assert correctness.
See: https://pmd.github.io/pmd-5.7.0/pmd-java/xref/net/sourceforge/pmd/lang/java/rule/codesize/NPathComplexityRule.html
```

Also, rename `Npath` to `NPath` everywhere.

2017-06-07 09:39 UTC, smola commented
@dpaz This needs a rebase to fix conflicts with the cyclomatic complexity PR, which is now merged.

2017-06-07 10:22 UTC, abeaumont approved these changes

2017-06-08 08:58 UTC, smola approved these changes

2017-06-08 09:03 UTC, smola commented
@dpaz can you rebase and squash all superfluous commits?

2017-06-08 10:52 UTC, dpaz commented
@smola done

2017-06-08 11:58 UTC, merged